AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CloudFormation template to deploy the initial lab environment.

Resources:
  LabS3BucketSource:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Join
        - "-"
        - - "lab-s3-source-bucket"
          - !Ref AWS::AccountId
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - /
                  - !Ref AWS::StackId
      AccessControl: Private
      Tags:
        - Key: "Name"
          Value: "lab-s3-source-bucket"

  LabS3BucketDestination:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Join
        - "-"
        - - "lab-s3-destination-bucket"
          - !Ref AWS::AccountId
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - /
                  - !Ref AWS::StackId
      AccessControl: Private
      Tags:
        - Key: "Name"
          Value: "lab-s3-destination-bucket"
